name: "🚀 publish npm package"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: 🚀 publish
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2.1.1
      - name: 🟢 node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org
      - name: 🚀 publish
        run: npm publish
        working-directory: .
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
